/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "docfilters-samples"

include(":docfilters-sample")
include(":convert-document-to-html")
include(":convert-document-to-markdown")
include(":convert-document-to-pdf")
include(":convert-document-to-png")
include(":convert-document-to-structured-xml")
include(":convert-document-to-thumbnail")
include(":convert-document-to-tiff-from-memory")
include(":convert-document-to-tiff-stream")
include(":convert-document-to-tiff")
include(":convert-document")
include(":extract-document-words")
