/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":docfilters-sample"))
}

tasks.withType<Jar> {
    mustRunAfter(":docfilters-sample:jar")
    
    manifest {
         attributes["Main-Class"] = "com.documentfilters.ConvertDocumentToTiff"
    }
    
    from({
        configurations.runtimeClasspath.get().filter { it.name.endsWith("jar") }.map { zipTree(it) }
    })
}

description = "Convert Document to TIFF"
