/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}


dependencies {
    // system(libs.com.documentfilters.documentfilters)
    api(files("./lib/ISYS11df.jar"))
}

description = "Document Filters Sample Base"
