/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    api(files("../../../bindings/java/lib/ISYS11df.jar"))
}

description = "Document Filters Sample Base"
